services:
  # Services can be built and launched using (but not limited to) the following commands:
  # docker compose --profile chatservers up --build
  # docker compose --profile addressingserver up --build
  # docker compose --profile client create --build
  # docker compose run --rm --service-ports client

  # Service for the initial Primary Addressing Server
  addressingserver:
    image: addressing-server:dev
    profiles: [ "addressingserver", "all" ]
    build:
      context: .
      dockerfile: Dockerfile.addressingserver
    restart: on-failure
    environment:
      # Defaults to hardcoded values if no .env file is present
      - AS_DEBUG_LEVEL=${AS_DEBUG_LEVEL:-3}
      - AS_CLIENT_PORT=${AS_CLIENT_PORT:-49800}
      - AS_REPLICA_PORT=${AS_REPLICA_PORT:-49801}
      - AS_CHATSERVER_PORT=${AS_CHATSERVER_PORT:-49802}
      - AS_ROLE=${AS_ROLE:-PRIMARY}
    ports:
      # Static port mapping for the Primary Addressing Server
      # Host:Container -> modify the host ports if you are experiencing issues with port mapping
      - "30001:49800"
      - "30002:49801"
      - "30003:49802"
      - "30004:5050"
    networks:
      - chat_network
    volumes:
      - ./data:/shared

  # Service for Replica addressing servers
  addressingserver-backup:
    extends:
      service: addressingserver
    profiles: [ "addressingserver-backup" ]
    environment:
      - AS_ROLE=REPLICA
    ports: !reset []

  chatserver:
    image: chat-server:dev
    profiles: [ "chatserver", "all"]
    build:
      context: .
      dockerfile: Dockerfile.chatserver
    ports:
      - 30100-30200:2424
      - 30201-30300:2425
    environment:
      - CS_DEBUG_LEVEL=${CS_DEBUG_LEVEL:-3}
      - CS_CLIENT_PORT=${CS_CLIENT_PORT:-2424}
      - CS_PEER_PORT=${CS_PEER_PORT:-2425}
      - DEBUG_LEVEL=${DEBUG_LEVEL:-1}
    networks:
      - chat_network
    volumes:
      - ./data:/shared:ro # read-only access for Chat Servers

  client:
    image: client:dev
    profiles: [ "client", "all" ]
    build:
      context: .
      dockerfile: Dockerfile.client
      tags:
        - "client:dev"
    environment:
      - CLIENT_DEBUG_LEVEL=${CLIENT_DEBUG_LEVEL:-0}
      - AS_CLIENT_PORT=${AS_CLIENT_PORT:-49800}
    networks:
      - chat_network
    tty: true
    stdin_open: true
    volumes:
      - ./data:/shared:ro # read-only access for Clients

networks:
  chat_network:
    driver: "bridge"

# This is different from the volume we define in a service. This is how we can ensure that any data...configs:
# ... that is created during the build or execution of the container(s), IS NOT deleted when the container is removed.
# This is very powerful because it allows us to update our repository (new version), and in turn build new containers...configs:
# ... without losing the data (chat logs) from previous versions.
# volumes:
#   db-data:  # Defines a named volume (currently unused in this config but can be used for persistent storage)