# Use non-Alpine base image for build
FROM gradle:jdk21 AS build

# Label the image
LABEL org.opencontainers.image.title="client"

# Set the working directory
WORKDIR /app/

# Copy the project files
COPY . .

# Build the project
RUN gradle buildClient --no-daemon

# Runtime stage
FROM eclipse-temurin:21-jdk

# Set the working directory
WORKDIR /app

# Copy the built jar from the build stage
COPY --from=build /app/client/build/libs/client.jar /app/client.jar

# Define the default program
ENTRYPOINT ["java", "-jar", "client.jar"]